#include "Keybinds.h"

int MOVE_FORWARD = ALLEGRO_KEY_W;
int MOVE_LEFT = ALLEGRO_KEY_A;
int MOVE_RIGHT = ALLEGRO_KEY_D;
int MOVE_BACK = ALLEGRO_KEY_S;
int QUIT = ALLEGRO_KEY_ESCAPE;
int DEBUG_RENDERING_TOGGLE = ALLEGRO_KEY_F1;
